name: Continuous Integration

on: push

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Format the `game` service
        working-directory: ./stirge-engine/services/game
        run: cargo fmt --check

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Lint the `game` service
        working-directory: ./stirge-engine/services/game
        run: cargo clippy --all-targets -- -D warnings